name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Publish microfunctions-auth
      uses: elgohr/Publish-Docker-Github-Action@3.02
      with:
        name: microfunctions/microfunctions-auth
        username: ${{ secrets.LOGIN_DOCKER }}
        password: ${{ secrets.PASSWORD_DOCKER }}
        tags: "main,${{ env.STATE_RELEASE_VERSION }}"
        tag_names: true
